type: rf

params:
  random_state: 42
  n_jobs: 1

search_space:
  n_estimators:
    low: 100
    high: 500
    step: 50
  max_depth:
    choices: [5, 10, 15, 20, null]
  min_samples_split:
    low: 2
    high: 10
  min_samples_leaf:
    low: 1
    high: 5